[Appearance]
style=Fusion
standard_dialogs=default
custom_palette=true
color_scheme_path=/home/archie/.config/qt5ct/colors/matugen.conf
icon_theme=Papirus-Dank

[Fonts]
fixed="JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0,Regular"
general="Inter,10,-1,5,50,0,0,0,0,0,Regular"

