#!/bin/bash
# Blocks direct edits to configs that are auto-generated from templates.
# Used as a Claude Code PreToolUse hook for Edit and Write tools.

FILE_PATH=$(jq -r '.tool_input.file_path // empty')

PROTECTED_FILES=(
  "$HOME/.config/i3/config"
)

for protected in "${PROTECTED_FILES[@]}"; do
  if [[ "$FILE_PATH" == "$protected" ]]; then
    jq -n '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: "This file is auto-generated by wpg. Edit the template at ~/.config/wpg/templates/ instead, then run wpg -s <wallpaper> to regenerate."
      }
    }'
    exit 0
  fi
done
