#!/usr/bin/env python3
"""PreToolUse guard for the patched-HyprPanel setup.

Forces every HyprPanel change through the patched launcher chain
(hyprpanel-launch -> hyprpanel-patched) and the matugen templates, so nothing
runs the stock binary unpatched or edits a file that gets regenerated.

Blocks:
  Edit/Write/MultiEdit on
    - the decoded JS bundle (*/dmFyIF-ags.js) — rewritten on every launch
    - /usr/share/hyprpanel/**            — stock install, overwritten by pacman
    - */hyprpanel/matugen-colors.scss    — generated by matugen each theme switch
  Bash that
    - runs hyprpanel-app                 — stock binary, no JS patches
    - runs 'hyprpanel -q'                — stock quit/restart path
    - launches 'gjs -m ... dmFyIF-ags.js' directly — bypasses the patcher

Explicitly NOT blocked (these are the supported paths):
    hyprpanel <cli-cmd> (rc, cfc, applyTheme, toggleWindow, ...),
    pkill/pgrep -f "gjs.*dmFyIF-ags.js", hyprpanel-launch, hyprpanel-patched,
    hyprpanel-watchdog.

Exit 0 = allow, exit 2 = block (stderr is surfaced back to Claude).
Fails open on any parse error so unrelated tool calls are never broken.
"""
import json
import re
import sys

try:
    data = json.load(sys.stdin)
except Exception:
    sys.exit(0)

tool = data.get("tool_name", "")
ti = data.get("tool_input", {}) or {}


def block(msg: str):
    sys.stderr.write(msg)
    sys.exit(2)


if tool in ("Edit", "Write", "MultiEdit"):
    fp = ti.get("file_path", "") or ti.get("path", "") or ""
    if re.search(r"dmFyIF-ags\.js$", fp):
        block(
            "BLOCKED: that is the decoded HyprPanel JS bundle, regenerated from "
            "scratch on every launch — any edit is lost on the next restart. Add "
            "or modify a sed/python patch in "
            "~/.config/hyprpanel/bin/hyprpanel-patched instead, then restart via "
            "the watchdog or hyprpanel-launch.\n"
        )
    if fp.startswith("/usr/share/hyprpanel/"):
        block(
            "BLOCKED: /usr/share/hyprpanel is the stock package install "
            "(overwritten by pacman, and it runs unpatched). Make the change as "
            "a patch in ~/.config/hyprpanel/bin/hyprpanel-patched instead.\n"
        )
    if fp.endswith("/hyprpanel/matugen-colors.scss"):
        block(
            "BLOCKED: matugen-colors.scss is generated by matugen and overwritten "
            "on every theme switch. Edit the template "
            "~/.config/matugen/templates/hyprpanel-colors instead.\n"
        )
    sys.exit(0)

if tool == "Bash":
    cmd = ti.get("command", "") or ""
    if re.search(r"\bhyprpanel-app\b", cmd):
        block(
            "BLOCKED: hyprpanel-app is the stock binary and skips all JS patches "
            "(modules stretch, menus misposition). Start/restart via "
            "~/.config/hyprpanel/bin/hyprpanel-launch, or just let the watchdog "
            "restart it.\n"
        )
    if re.search(r"\bhyprpanel\s+-q\b", cmd):
        block(
            "BLOCKED: 'hyprpanel -q' is the stock quit/restart path. To restart, "
            "run ~/.config/hyprpanel/bin/hyprpanel-launch (kill-only is "
            'pkill -f "gjs.*dmFyIF-ags.js").\n'
        )
    if re.search(r"\bgjs\s+-m\b.*dmFyIF-ags\.js", cmd):
        block(
            "BLOCKED: launching gjs directly on the bundle bypasses every patch. "
            "Use ~/.config/hyprpanel/bin/hyprpanel-launch (which runs "
            "hyprpanel-patched to decode + patch + launch).\n"
        )
    sys.exit(0)

sys.exit(0)
