[config]
color_scheme = "dark"

[templates.spicetify-colors]
input_path = "~/.config/matugen/templates/spicetify-colors"
output_path = "~/.config/spicetify/Themes/matugen/color.ini"

[templates.discord-colors]
input_path = "~/.config/matugen/templates/discord-colors"
output_path = "~/.config/BetterDiscord/themes/matugen.theme.css"

[templates.notion-colors]
input_path = "~/.config/matugen/templates/notion-colors"
output_path = "~/.cache/matugen/notion-colors.css"


[templates.gtk4-vars]
input_path = "~/.config/matugen/templates/gtk4-vars"
output_path = "~/.config/gtk-4.0/dank-vars.css"

[templates.vscode-colors]
input_path = "~/.config/matugen/templates/vscode-colors"
output_path = "~/.vscode/extensions/matugen-theme/themes/matugen.json"

[templates.nvim-colors]
input_path = "~/.config/matugen/templates/nvim-colors"
output_path = "~/.config/nvim/colors/matugen.lua"

[templates.satty-config]
input_path = "~/.config/matugen/templates/satty-config"
output_path = "~/.config/satty/config.toml"


[templates.hypr-borders]
input_path = "~/.config/matugen/templates/hypr-borders"
output_path = "~/.config/hypr/borders.lua"
