-- Auto-generated by matugen: neutral light borders (never the accent)
hl.config({
    general = {
        col = {
            active_border   = "rgb(f8e1ea)",
            inactive_border = "rgb(716067)",
        },
    },
})
