-- Auto-generated by matugen: neutral light borders (never the accent)
hl.config({
    general = {
        col = {
            active_border   = "rgb(e4e6f3)",
            inactive_border = "rgb(61646f)",
        },
    },
})
