-- Auto-generated by matugen: neutral light borders (never the accent)
hl.config({
    general = {
        col = {
            active_border   = "rgb(e1e7f2)",
            inactive_border = "rgb(5e656e)",
        },
    },
})
