-- Hyprland configuration.
--
-- Ported from hyprland.conf — hyprlang is deprecated as of Hyprland 0.55.
-- API reference:    /usr/share/hypr/stubs/hl.meta.lua
-- Default example:  /usr/share/hypr/hyprland.lua
-- Wiki:             https://wiki.hypr.land/Configuring/

-- Border and shadow colors, generated by matugen.
-- Never edit colors.lua by hand — edit ~/.config/matugen/templates/hyprland-colors.
require("colors")


------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "DP-2",
    mode     = "5120x1440@120",
    position = "0x0",
    scale    = 1,
})

-- The virtual output for remote streaming (Sunshine/Moonlight from the MacBook)
-- is not declared here. Hyprland names virtual outputs HEADLESS-<n> with a
-- counter that increments per process and offers no way to choose the name, so a
-- static rule would silently stop matching. ~/.local/bin/remote-display creates
-- it and applies geometry to whatever name it actually got. It is the single
-- source of truth for that output; see the autostart block below.


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "nautilus --new-window"
local menu        = "rofi -show drun -theme ~/.config/rofi/launchers/type-1/style-5.rasi"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprland-session.target")

    -- Polkit authentication agent. Without one, anything needing elevation
    -- (nemo mounting a disk, gparted, etc.) fails silently: polkitd is running
    -- but has no agent to raise a password prompt through.
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("awww-daemon")

    -- Headless output for remote streaming. Fires once per Hyprland start (not
    -- on reload), so it will not stack up HEADLESS-2, -3 ... on every reload.
    -- Also re-points Sunshine's output_name at the name the output actually got.
    hl.exec_cmd("~/.local/bin/remote-display up")

    -- Watchdog owns the hyprpanel lifecycle: spawns it as a child (so gdb can
    -- attach via ptrace_scope=1), monitors the heartbeat file, and restarts on
    -- freeze with a circuit breaker. hyprpanel-launch is no longer wired here so
    -- the watchdog is the sole parent.
    hl.exec_cmd("~/.config/hyprpanel/bin/hyprpanel-watchdog")

    hl.exec_cmd("spotify --remote-debugging-port=9222")
    hl.exec_cmd("discord")
    hl.exec_cmd("notion-app")
    hl.exec_cmd("mullvad-vpn")
    hl.exec_cmd("~/.local/bin/hyprsunset-auto")
    hl.exec_cmd("sleep 5 && claude-desktop")
    hl.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-start.sh --hidden")
end)

-- A reload re-applies monitor config from this file, and this file deliberately
-- does not declare the headless output, so a reload resets it to the 1920x1080
-- default. Re-assert it afterwards. remote-display is idempotent: it reuses the
-- existing output rather than creating another one.
hl.on("config.reloaded", function()
    hl.exec_cmd("~/.local/bin/remote-display up")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")


-----------------------
----- PERMISSIONS -----
-----------------------

-- Permission changes require a Hyprland restart and are not applied on-the-fly
-- for security reasons.

-- hl.config({ ecosystem = { enforce_permissions = true } })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        -- border colors set by matugen via colors.lua

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = false,
        },

        blur = {
            enabled  = false,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true, -- You probably want this
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },

    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        repeat_rate  = 50,
        repeat_delay = 300,

        follow_mouse = 2,

        sensitivity   = -0.4, -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "adaptive",

        touchpad = {
            natural_scroll = false,
        },
    },
})


--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutQuint",    { type = "bezier", points = { {0.23, 1},     {0.32, 1} } })
hl.curve("easeInOutCubic",  { type = "bezier", points = { {0.65, 0.05},  {0.36, 1} } })
hl.curve("linear",          { type = "bezier", points = { {0, 0},        {1, 1} } })
hl.curve("almostLinear",    { type = "bezier", points = { {0.5, 0.5},    {0.75, 1} } })
hl.curve("quick",           { type = "bezier", points = { {0.15, 0},     {0.1, 1} } })
hl.curve("workspaceSwitch", { type = "bezier", points = { {0.51, -0.04}, {0, 1} } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint",    style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",          style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint",    style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",          style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 9,    bezier = "workspaceSwitch", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 9,    bezier = "workspaceSwitch", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 9,    bezier = "workspaceSwitch", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })


-- Dynamic gaps for ultrawide: decrease side gaps as tiled window count increases.
-- Scoped to DP-2 with m[...]: these side gaps are sized for a 5120px monitor and
-- would leave ~150px of usable width on the 1512px logical headless output.
hl.workspace_rule({ workspace = "m[DP-2] w[t1-2]",  gaps_out = { top = 20, right = 680, bottom = 20, left = 680 } })
hl.workspace_rule({ workspace = "m[DP-2] w[t3-4]",  gaps_out = { top = 20, right = 340, bottom = 20, left = 340 } })
hl.workspace_rule({ workspace = "m[DP-2] w[t5-99]", gaps_out = { top = 20, right = 154, bottom = 20, left = 154 } })

-- Workspace 10 (SUPER+0) is the remote workspace; remote-display pins it to the
-- headless output once that output exists and its name is known. Pinning 1-9 to
-- DP-2 here has to happen in config rather than in the script, because it must
-- be loaded before the headless output is created — otherwise the new output
-- claims workspace 1 and SUPER+1 starts focusing a screen that is not there.
for i = 1, 9 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "DP-2" })
end


---------------
---- INPUT ----
---------------

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

-- Example per-device config
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Open HyprPanel dashboard on Super + Ctrl
hl.bind(mainMod .. " + Control_L", hl.dsp.exec_cmd("hyprpanel toggleWindow dashboardmenu"), { desc = "Dashboard" })

hl.bind(mainMod .. " + Q",              hl.dsp.exec_cmd(terminal),                          { desc = "Terminal" })
hl.bind(mainMod .. " + Return",         hl.dsp.exec_cmd(terminal),                          { desc = "Terminal" })
hl.bind(mainMod .. " + C",              hl.dsp.window.center(),                             { desc = "Center Window" })
hl.bind(mainMod .. " + SHIFT + C",      hl.dsp.exec_cmd("gnome-calculator"),                { desc = "Calculator" })
hl.bind(mainMod .. " + SHIFT + Q",      hl.dsp.window.close(),                              { desc = "Close Window" })
hl.bind(mainMod .. " + SHIFT + E",      hl.dsp.exec_cmd(fileManager),                       { desc = "File Manager" })
hl.bind(mainMod .. " + SHIFT + space",  hl.dsp.window.float({ action = "toggle" }),         { desc = "Toggle Floating" })
hl.bind(mainMod .. " + space",          hl.dsp.exec_cmd("~/.local/bin/dismiss-notifications"), { desc = "Dismiss Notifications" })
hl.bind(mainMod .. " + D",              hl.dsp.exec_cmd(menu),                              { desc = "App Launcher" })
hl.bind(mainMod .. " + SHIFT + R",      hl.dsp.exec_cmd('hyprctl reload && notify-send -u low -t 2000 "Hyprland" "Config reloaded"'), { desc = "Reload Config" })
hl.bind(mainMod .. " + slash",          hl.dsp.exec_cmd("~/.local/bin/keybind-cheatsheet"), { desc = "Keybind Cheatsheet" })
hl.bind(mainMod .. " + W",              hl.dsp.exec_cmd("~/.local/bin/wallpaper-picker"),   { desc = "Wallpaper Picker" })
hl.bind(mainMod .. " + SHIFT + W",      hl.dsp.exec_cmd("~/.local/bin/theme-switch"),       { desc = "Switch Theme/Wallpaper" })
hl.bind(mainMod .. " + ALT + W",        hl.dsp.exec_cmd("~/.config/hyprkit/theme-switch/backend-picker"), { desc = "Theme Backend Picker" })
hl.bind(mainMod .. " + ALT + L",        hl.dsp.exec_cmd("hyprlock"),                        { desc = "Lock Screen" })
hl.bind(mainMod .. " + SHIFT + period", hl.dsp.exec_cmd("playerctl -p spotify next"),       { desc = "Spotify Next" })
hl.bind(mainMod .. " + SHIFT + comma",  hl.dsp.exec_cmd("playerctl -p spotify previous"),   { desc = "Spotify Previous" })
hl.bind(mainMod .. " + SHIFT + S",      hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { desc = "Spotify Play/Pause" })

-- Cycle through windows and raise to top
hl.bind(mainMod .. " + Tab", function()
    hl.dispatch(hl.dsp.window.cycle_next())
    hl.dispatch(hl.dsp.window.bring_to_top())
end, { desc = "Cycle Windows" })

hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(),                      { desc = "Pseudo (dwindle)" })
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -a -f hex"),     { desc = "Color Picker" })
hl.bind(mainMod .. " + V",         hl.dsp.layout("togglesplit"),                { desc = "Toggle Split (dwindle)" })
hl.bind(mainMod .. " + S",         hl.dsp.focus({ workspace = 8 }),             { desc = "Spotify Workspace" })
-- Was: hyprctl --batch "dispatch resizeactive exact …; dispatch centerwindow".
-- `hyprctl dispatch` only accepts Lua expressions under a Lua config, so this
-- is now native. resize({ exact = true }) is verified to set an absolute size.
hl.bind(mainMod .. " + X", function()
    hl.dispatch(hl.dsp.window.resize({ x = 2540, y = 1300, exact = true }))
    hl.dispatch(hl.dsp.window.center())
end, { desc = "Resize + Center" })

-- Move focus with mainMod + arrow keys / vim keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { desc = "Focus Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { desc = "Focus Right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { desc = "Focus Up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { desc = "Focus Down" })
hl.bind(mainMod .. " + H",     hl.dsp.focus({ direction = "left" }),  { desc = "Focus Left" })
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }), { desc = "Focus Right" })
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "up" }),    { desc = "Focus Up" })
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "down" }),  { desc = "Focus Down" })

-- Move focused window with mainMod + SHIFT + vim keys
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }),  { desc = "Move Window Left" })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }),  { desc = "Move Window Down" })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }),    { desc = "Move Window Up" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }), { desc = "Move Window Right" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through existing workspaces with mainMod + scroll (no wrap)
hl.bind(mainMod .. " + mouse_down", hl.dsp.exec_cmd("~/.local/bin/workspace-switch +1"))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.exec_cmd("~/.local/bin/workspace-switch -1"))

-- Switch workspaces with mainMod + </> (no wrap)
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("~/.local/bin/workspace-switch +1"), { desc = "Next Workspace" })
hl.bind(mainMod .. " + comma",  hl.dsp.exec_cmd("~/.local/bin/workspace-switch -1"), { desc = "Previous Workspace" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl -p spotify next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl -p spotify previous"),   { locked = true })

-- Screenshot with grimblast (same tool as hyprpanel)
hl.bind("Print", hl.dsp.exec_cmd("/usr/share/hyprpanel/scripts/snapshot.sh area"), { desc = "Screenshot (Area)" })

-- YCOMBO — AI & Dev HN feed
hl.bind(mainMod .. " + F5",           hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-refresh.sh"),    { desc = "YCombo Refresh" })
hl.bind(mainMod .. " + Y",            hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-toggle.sh"),     { desc = "YCombo Toggle" })
hl.bind(mainMod .. " + CTRL + Up",    hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-resize.sh +h"),  { desc = "YCombo Taller" })
hl.bind(mainMod .. " + CTRL + Down",  hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-resize.sh -h"),  { desc = "YCombo Shorter" })
hl.bind(mainMod .. " + CTRL + Right", hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-resize.sh +w"),  { desc = "YCombo Wider" })
hl.bind(mainMod .. " + CTRL + Left",  hl.dsp.exec_cmd("/home/archie/Documents/Github-Projects/ycombo/ycombo-resize.sh -w"),  { desc = "YCombo Narrower" })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Wofi - fade only (no resize/slide animation)
hl.layer_rule({ name = "wofi-fade", match = { namespace = "wofi" }, animation = "fade" })

-- Rofi - fade only (no resize/slide animation)
hl.layer_rule({ name = "rofi-fade", match = { namespace = "rofi" }, animation = "fade" })

-- Wallpaper picker - fade
hl.layer_rule({ name = "wallpaper-picker-fade", match = { namespace = "wallpaper-picker" }, animation = "fade" })

-- YCOMBO - disable resize animation
hl.layer_rule({ name = "ycombo-no-anim", match = { namespace = "ycombo" }, animation = "none" })

-- Float all windows by default
hl.window_rule({
    name  = "float-all",
    match = { class = ".*" },

    float = true,
})

-------------------------------------------------------------
--- DEFAULT GEOMETRY — PRIMARY APPLICATION WINDOWS ONLY   ---
-------------------------------------------------------------
-- The default size/centre must not touch dialogs, menus, dropdowns or tooltips.
-- Those are separate toplevels, so a plain `class = ".*"` size rule stretches
-- them to the full 2540x1300 instead of leaving them at their natural size next
-- to whatever opened them.
--
-- match.float is the discriminator. By the time window rules are evaluated,
-- CHyprXWaylandManager::shouldBeFloated() has already run and set the floating
-- state, and it floats anything the client presents as transient:
--   X11     - _NET_WM_WINDOW_TYPE_{DIALOG,MENU,DROPDOWN_MENU,POPUP_MENU,TOOLTIP,
--             TOOLBAR,UTILITY,SPLASH,DOCK}, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE,
--             modal windows, transients, override-redirect windows, anything
--             with a parent, and fixed-size windows (min hints == max hints)
--   Wayland - any xdg_toplevel with a parent, or one with a fixed size
--
-- `float = true` above does not interfere: it is staged as static_.floating and
-- only committed after the rule pass, so it never feeds back into this match.
--
-- So match.float = false means "the client did not ask to be transient", i.e. a
-- primary application window. Everything else keeps the geometry it requested.
-- This is toolkit-agnostic (GTK, Qt, Electron, Java, wine) — no per-app rules.
hl.window_rule({
    name  = "default-size-primary-only",
    match = { class = ".*", float = false },

    size   = "2540 1300",
    center = true,
})

-------------------------------------------------------------
--- PER-APP SIZES (these intentionally win over the above) --
-------------------------------------------------------------

-- Mullvad — override the catch-all size so it keeps its own dimensions
hl.window_rule({
    name  = "mullvad-size",
    match = { class = "^(mullvad-vpn|Mullvad VPN)$" },

    size = "320 568",
})

hl.window_rule({
    name  = "mullvad-workspace",
    match = { class = "^(mullvad-vpn|Mullvad VPN)$" },

    workspace = "5 silent",
})

hl.window_rule({
    name  = "kitty-size",
    match = { class = "^(kitty)$" },

    size = "1900 1000",
})

hl.window_rule({
    name  = "nautilus-size",
    match = { class = "^(org.gnome.Nautilus)$" },

    size = "1900 1000",
})

hl.window_rule({
    name  = "file-picker-size",
    match = { class = "^(xdg-desktop-portal-gtk)$" },

    size = "1580 850",
})

hl.window_rule({
    name  = "calculator-size",
    match = { class = "^(org.gnome.Calculator)$" },

    size = "360 615",
})

-- Example window rules that are useful

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    name  = "spotify-workspace",
    match = { class = "^(Spotify)$" },

    workspace = "8 silent",
})

hl.window_rule({
    name  = "discord-workspace",
    match = { class = "^(discord)$" },

    workspace = "9 silent",
})

hl.window_rule({
    name  = "notion-workspace",
    match = { class = "^(Notion)$" },

    workspace = "7 silent",
})

hl.window_rule({
    name  = "claude-workspace",
    match = { class = "^(com\\.anthropic\\.claude-desktop)$" },

    workspace = "6 silent",
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


-----------------
---- PLUGINS ----
-----------------

-- hl.plugin.load("/home/archie/Documents/Github-Projects/hyprlax/hyprlax.so")

-- hl.config({
--     plugin = {
--         hyprlax = {
--             parallax_strength = 0.15,
--             enabled = 1,
--         },
--     },
-- })
