-- Hyprland configuration.
--
-- Ported from hyprland.conf — hyprlang is deprecated as of Hyprland 0.55.
-- API reference:    /usr/share/hypr/stubs/hl.meta.lua
-- Default example:  /usr/share/hypr/hyprland.lua
-- Wiki:             https://wiki.hypr.land/Configuring/

-- Border/group colours are generated by DankMaterialShell (matugen) into
-- ~/.config/hypr/dms/colors.lua and ~/.config/hypr/borders.lua on every wallpaper
-- change. They are read with io rather than require so Hyprland does not register
-- them for autoreload: that reload stalled the shell mid-crossfade. theme-apply pushes the same colours live via hyprctl keywords.
local function load_colours(name)
    local f = io.open(os.getenv("HOME") .. "/.config/hypr/" .. name, "r")
    if not f then return end
    local chunk, err = load(f:read("*a"), "@" .. name)
    f:close()
    if chunk then chunk() else print("hyprland.lua: " .. tostring(err)) end
end
load_colours("dms/colors.lua")
load_colours("borders.lua")

-- Machine-local additions for projects that are not published: autostart commands,
-- keybinds and layer rules. They live in ~/.config/hypr/local.lua, which this repo
-- deliberately does not track — it is public, and an unreleased project's name and
-- paths are not something a dotfiles repo should announce. Read the same way as the
-- colours above (io + load, never require) so Hyprland does not watch it for reload.
-- The file returns a table:
--   return {
--     autostart   = { "cmd --flag" },
--     binds       = { { key = "SUPER + Y", cmd = "…", desc = "…" } },
--     layer_rules = { { name = "…", match = { namespace = "…" }, animation = "none" } },
--   }
local local_conf = {}
do
    local f = io.open(os.getenv("HOME") .. "/.config/hypr/local.lua", "r")
    if f then
        local chunk, err = load(f:read("*a"), "@local.lua")
        f:close()
        if chunk then
            local ok, t = pcall(chunk)
            if ok and type(t) == "table" then
                local_conf = t
            else
                print("hyprland.lua: local.lua did not return a table: " .. tostring(t))
            end
        else
            print("hyprland.lua: " .. tostring(err))
        end
    end
end


------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "DP-2",
    mode     = "5120x1440@120",
    position = "0x0",
    scale    = 1,
})


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty -1"  -- single-instance: new windows attach to the running kitty (no cold GL/font start)
local fileManager = "nautilus --new-window"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprland-session.target")

    -- KDE Connect (clipboard/share sync with the MacBook). Must run inside the
    -- session so it sees the Wayland clipboard; kills any ssh-spawned instance
    -- that started without WAYLAND_DISPLAY. Pairing state lives on disk and
    -- survives the restart.
    hl.exec_cmd("sh -c 'pkill -x kdeconnectd; sleep 1; exec /usr/lib/kdeconnectd'")

    -- Session daemons (polkit agent, wallpaper daemon, clipboard history,
    -- idle) are systemd user units bound to graphical-session.target, so they
    -- get supervision and restart-on-failure for free. Enable with
    --   systemctl --user enable hyprpolkitagent cliphist (idle/lock/wallpaper are DMS built-ins)

    -- Watchdog owns the hyprpanel lifecycle: spawns it as a child (so gdb can
    -- attach via ptrace_scope=1), monitors the heartbeat file, and restarts on
    -- freeze with a circuit breaker. hyprpanel-launch is no longer wired here so
    -- the watchdog is the sole parent.
    -- Shell: DankMaterialShell via systemd (dms.service, WantedBy graphical-session.target)

    -- Electron apps are staggered: four of them launching at once contend for
    -- GPU and disk with the bar's own startup.
    hl.exec_cmd("~/.local/bin/hyprsunset-auto")
    hl.exec_cmd("mullvad-vpn")
    hl.exec_cmd("sleep 3 && spotify --remote-debugging-port=9332")
    hl.exec_cmd("sleep 6 && discord")
    hl.exec_cmd("sleep 9 && notion-app")
    -- claude-desktop and chatgpt are launched on demand, not at boot.

    -- Anything ~/.config/hypr/local.lua wants started with the session.
    for _, cmd in ipairs(local_conf.autostart or {}) do
        hl.exec_cmd(cmd)
    end
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("HYPRCURSOR_SIZE", "24")
-- Pin GTK apps (libadwaita too) to the theme-apply theme so the Matugen-A/B flip recolours them live.
-- Same value as ~/.config/environment.d/60-gtk-theme.conf; Hyprland only applies env at launch.
hl.env("GTK_THEME", "Matugen-A")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")


-----------------------
----- PERMISSIONS -----
-----------------------

-- Permission changes require a Hyprland restart and are not applied on-the-fly
-- for security reasons.

-- hl.config({ ecosystem = { enforce_permissions = true } })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        -- Look A: flat tonal Material 3. 2px tonal borders; depth comes from tonal surfaces; no window shadows (user preference).
        gaps_in  = 6,
        gaps_out = 12,
        border_size = 2,

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 16,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = false,
            range        = 24,
            render_power = 3,
            color        = "rgba(00000055)",
            color_inactive = "rgba(00000033)",
        },

        blur = {
            enabled    = false,
            size       = 8,
            passes     = 2,
            noise      = 0.015,
            brightness = 1.0,
            vibrancy   = 0.17,
            xray       = false,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true, -- You probably want this
    },

    master = {
        new_status = "master",
    },

    misc = {
        vrr = 2,                         -- adaptive sync for fullscreen only (games/video)
        force_default_wallpaper = 0,     -- DMS paints the whole output; skip decoding the stock wallpaper texture
        disable_hyprland_logo   = true,  -- no logo texture in VRAM, no occluded draw behind the shell
        disable_splash_rendering = true,
    },

    render = {
        new_render_scheduling = true,   -- dynamic triple buffering when a frame misses vblank (7.4 Mpx at 120 Hz)
        cm_enabled = false,             -- SDR panel, XRGB8888: skip the colour-management pass per surface
        direct_scanout = 2,              -- scanout fullscreen games directly, no compositor copy
    },
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        repeat_rate  = 50,
        repeat_delay = 300,

        follow_mouse = 2,

        sensitivity   = -0.4, -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "adaptive",

        touchpad = {
            natural_scroll = false,
        },
    },
})


--------------------
---- ANIMATIONS ----
--------------------

hl.curve("easeOutQuint",    { type = "bezier", points = { {0.23, 1},     {0.32, 1} } })
hl.curve("easeInOutCubic",  { type = "bezier", points = { {0.65, 0.05},  {0.36, 1} } })
hl.curve("linear",          { type = "bezier", points = { {0, 0},        {1, 1} } })
hl.curve("almostLinear",    { type = "bezier", points = { {0.5, 0.5},    {0.75, 1} } })
hl.curve("quick",           { type = "bezier", points = { {0.15, 0},     {0.1, 1} } })
hl.curve("workspaceSwitch", { type = "bezier", points = { {0.51, -0.04}, {0, 1} } })
-- Springs (Hyprland 0.56): mass / stiffness / dampening, macOS-like settle
hl.curve("easy",  { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })
hl.curve("snappy",{ type = "spring", mass = 1, stiffness = 320, dampening = 30 })
hl.curve("gentle",  { type = "spring", mass = 1, stiffness = 110, dampening = 20 })
hl.curve("swift",   { type = "spring", mass = 1, stiffness = 400, dampening = 32 }) -- ~210 ms settle, half of gentle

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, spring = "snappy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  spring = "snappy",          style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",          style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, spring = "snappy" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint",    style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",          style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 3.5, spring = "swift",            style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 3.5, spring = "gentle",           style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 3.5, spring = "gentle",           style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })


-- Dynamic gaps for ultrawide: decrease side gaps as tiled window count increases.
-- These side gaps are sized for the 5120px monitor.
hl.workspace_rule({ workspace = "m[DP-2] w[t1-2]",  gaps_out = { top = 20, right = 680, bottom = 20, left = 680 } })
hl.workspace_rule({ workspace = "m[DP-2] w[t3-4]",  gaps_out = { top = 20, right = 340, bottom = 20, left = 340 } })
hl.workspace_rule({ workspace = "m[DP-2] w[t5-99]", gaps_out = { top = 20, right = 154, bottom = 20, left = 154 } })


---------------
---- INPUT ----
---------------

hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})

-- Example per-device config
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Open HyprPanel dashboard on Super + Ctrl
hl.bind(mainMod .. " + Control_L", hl.dsp.exec_cmd("dms ipc call control-center toggle"), { desc = "Control Centre" })
hl.bind(mainMod .. " + N",         hl.dsp.exec_cmd("dms ipc call notifications toggle"), { desc = "Notification Centre" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"),     { desc = "Clipboard History" })
hl.bind(mainMod .. " + Escape",    hl.dsp.exec_cmd("dms ipc call powermenu toggle"),     { desc = "Power Menu" })

hl.bind(mainMod .. " + Q",              hl.dsp.exec_cmd(terminal),                          { desc = "Terminal" })
hl.bind(mainMod .. " + Return",         hl.dsp.exec_cmd(terminal),                          { desc = "Terminal" })
hl.bind(mainMod .. " + C",              hl.dsp.window.center(),                             { desc = "Center Window" })
hl.bind(mainMod .. " + SHIFT + C",      hl.dsp.exec_cmd("gnome-calculator"),                { desc = "Calculator" })
hl.bind(mainMod .. " + SHIFT + Q",      hl.dsp.window.close(),                              { desc = "Close Window" })
hl.bind(mainMod .. " + SHIFT + E",      hl.dsp.exec_cmd(fileManager),                       { desc = "File Manager" })
hl.bind(mainMod .. " + SHIFT + space",  hl.dsp.window.float({ action = "toggle" }),         { desc = "Toggle Floating" })
hl.bind(mainMod .. " + space",          hl.dsp.exec_cmd("dms ipc call notifications clearAll"), { desc = "Dismiss Notifications" })
hl.bind(mainMod .. " + D",              hl.dsp.exec_cmd("dms ipc call spotlight toggle"),   { desc = "App Launcher" })
hl.bind(mainMod .. " + SHIFT + R",      hl.dsp.exec_cmd('hyprctl reload && notify-send -u low -t 2000 "Hyprland" "Config reloaded"'), { desc = "Reload Config" })
hl.bind(mainMod .. " + slash",          hl.dsp.exec_cmd("~/.local/bin/keybind-cheatsheet"), { desc = "Keybind Cheatsheet" })
hl.bind(mainMod .. " + W",              hl.dsp.exec_cmd("dms ipc call dash open wallpaper"), { desc = "Wallpaper Picker" })
hl.bind(mainMod .. " + SHIFT + W",      hl.dsp.exec_cmd("~/.local/bin/theme-switch --next"), { desc = "Next Wallpaper/Theme" })
hl.bind(mainMod .. " + ALT + L",        hl.dsp.exec_cmd("dms ipc call lock lock"),          { desc = "Lock Screen" })
hl.bind(mainMod .. " + SHIFT + period", hl.dsp.exec_cmd("playerctl -p spotify next"),       { desc = "Spotify Next" })
hl.bind(mainMod .. " + SHIFT + comma",  hl.dsp.exec_cmd("playerctl -p spotify previous"),   { desc = "Spotify Previous" })
hl.bind(mainMod .. " + SHIFT + S",      hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { desc = "Spotify Play/Pause" })

-- Cycle through windows and raise to top
hl.bind(mainMod .. " + Tab", function()
    hl.dispatch(hl.dsp.window.cycle_next())
    hl.dispatch(hl.dsp.window.bring_to_top())
end, { desc = "Cycle Windows" })

hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo(),                      { desc = "Pseudo (dwindle)" })
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -a -f hex"),     { desc = "Color Picker" })
hl.bind(mainMod .. " + V",         hl.dsp.layout("togglesplit"),                { desc = "Toggle Split (dwindle)" })
hl.bind(mainMod .. " + S",         hl.dsp.focus({ workspace = 8 }),             { desc = "Spotify Workspace" })
-- Was: hyprctl --batch "dispatch resizeactive exact …; dispatch centerwindow".
-- `hyprctl dispatch` only accepts Lua expressions under a Lua config, so this
-- is now native. resize({ exact = true }) is verified to set an absolute size.
hl.bind(mainMod .. " + X", function()
    hl.dispatch(hl.dsp.window.resize({ x = 2540, y = 1300, exact = true }))
    hl.dispatch(hl.dsp.window.center())
end, { desc = "Resize + Center" })

-- Move focus with mainMod + arrow keys / vim keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),  { desc = "Focus Left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }), { desc = "Focus Right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),    { desc = "Focus Up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),  { desc = "Focus Down" })
hl.bind(mainMod .. " + H",     hl.dsp.focus({ direction = "left" }),  { desc = "Focus Left" })
hl.bind(mainMod .. " + L",     hl.dsp.focus({ direction = "right" }), { desc = "Focus Right" })
hl.bind(mainMod .. " + K",     hl.dsp.focus({ direction = "up" }),    { desc = "Focus Up" })
hl.bind(mainMod .. " + J",     hl.dsp.focus({ direction = "down" }),  { desc = "Focus Down" })

-- Move focused window with mainMod + SHIFT + vim keys
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }),  { desc = "Move Window Left" })
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }),  { desc = "Move Window Down" })
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }),    { desc = "Move Window Up" })
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }), { desc = "Move Window Right" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Scroll through existing workspaces with mainMod + scroll (no wrap)
hl.bind(mainMod .. " + mouse_down", hl.dsp.exec_cmd("~/.local/bin/workspace-switch +1"))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.exec_cmd("~/.local/bin/workspace-switch -1"))

-- Switch workspaces with mainMod + </> (no wrap)
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("~/.local/bin/workspace-switch +1"), { desc = "Next Workspace" })
hl.bind(mainMod .. " + comma",  hl.dsp.exec_cmd("~/.local/bin/workspace-switch -1"), { desc = "Previous Workspace" })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl -p spotify next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl -p spotify play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl -p spotify previous"),   { locked = true })

-- Screenshots: grim + slurp + satty (~/.local/bin/screenshot)
hl.bind("Print",                    hl.dsp.exec_cmd("~/.local/bin/screenshot area"),   { desc = "Screenshot area -> clipboard" })
hl.bind("SHIFT + Print",            hl.dsp.exec_cmd("~/.local/bin/screenshot edit"),   { desc = "Screenshot area -> annotate" })
hl.bind(mainMod .. " + Print",      hl.dsp.exec_cmd("~/.local/bin/screenshot window"), { desc = "Screenshot window" })
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("~/.local/bin/screenshot output"), { desc = "Screenshot monitor" })
hl.bind(mainMod .. " + ALT + R",     hl.dsp.exec_cmd("~/.local/bin/app-relaunch"),        { desc = "Relaunch focused app (fresh theme)" })

-- Keybinds from ~/.config/hypr/local.lua. `key` is the full combination, e.g.
-- "SUPER + Y" or "SUPER + CTRL + Left"; mainMod above is the SUPER these use.
for _, b in ipairs(local_conf.binds or {}) do
    if b.key and b.cmd then
        hl.bind(b.key, hl.dsp.exec_cmd(b.cmd), { desc = b.desc or b.cmd })
    end
end


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Wofi - fade only (no resize/slide animation)

-- Rofi - fade only (no resize/slide animation)
hl.layer_rule({ name = "dms-noanim", match = { namespace = "dms" }, no_anim = true })


-- Wallpaper picker - fade

-- Layer rules from ~/.config/hypr/local.lua, passed through untouched.
for _, r in ipairs(local_conf.layer_rules or {}) do
    hl.layer_rule(r)
end

-- Float all windows by default
hl.window_rule({
    name  = "float-all",
    match = { class = ".*" },

    float = true,
})

-------------------------------------------------------------
--- DEFAULT GEOMETRY — PRIMARY APPLICATION WINDOWS ONLY   ---
-------------------------------------------------------------
-- The default size/centre must not touch dialogs, menus, dropdowns or tooltips.
-- Those are separate toplevels, so a plain `class = ".*"` size rule stretches
-- them to the full 2540x1300 instead of leaving them at their natural size next
-- to whatever opened them.
--
-- match.float is the discriminator. By the time window rules are evaluated,
-- CHyprXWaylandManager::shouldBeFloated() has already run and set the floating
-- state, and it floats anything the client presents as transient:
--   X11     - _NET_WM_WINDOW_TYPE_{DIALOG,MENU,DROPDOWN_MENU,POPUP_MENU,TOOLTIP,
--             TOOLBAR,UTILITY,SPLASH,DOCK}, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE,
--             modal windows, transients, override-redirect windows, anything
--             with a parent, and fixed-size windows (min hints == max hints)
--   Wayland - any xdg_toplevel with a parent, or one with a fixed size
--
-- `float = true` above does not interfere: it is staged as static_.floating and
-- only committed after the rule pass, so it never feeds back into this match.
--
-- So match.float = false means "the client did not ask to be transient", i.e. a
-- primary application window. Everything else keeps the geometry it requested.
-- This is toolkit-agnostic (GTK, Qt, Electron, Java, wine) — no per-app rules.
hl.window_rule({
    name  = "default-size-primary-only",
    match = { class = ".*", float = false },

    size   = "2540 1300",
    center = true,
})

-------------------------------------------------------------
--- PER-APP SIZES (these intentionally win over the above) --
-------------------------------------------------------------

-- Mullvad — override the catch-all size so it keeps its own dimensions
hl.window_rule({
    name  = "mullvad-size",
    match = { class = "^(mullvad-vpn|Mullvad VPN)$" },

    size = "320 568",
})

hl.window_rule({
    name  = "mullvad-workspace",
    match = { class = "^(mullvad-vpn|Mullvad VPN)$" },

    workspace = "5 silent",
})

hl.window_rule({
    name  = "kitty-size",
    match = { class = "^(kitty)$" },

    size = "1900 1000",
})

hl.window_rule({
    name  = "nautilus-size",
    match = { class = "^(org.gnome.Nautilus)$" },

    size = "1900 1000",
})

hl.window_rule({
    name  = "file-picker-size",
    match = { class = "^(xdg-desktop-portal-gtk)$" },

    size = "1580 850",
})

hl.window_rule({
    name  = "calculator-size",
    match = { class = "^(org.gnome.Calculator)$" },

    size = "360 615",
})

-- pavucontrol 6.x is GTK4: a plain resizable toplevel, so the catch-all
-- primary-window rule would stretch it to 2540x1300. Give it a mixer-sized window.
hl.window_rule({
    name  = "pavucontrol-size",
    match = { class = "^(org\\.pulseaudio\\.pavucontrol)$" },

    size = "900 800",
})

-- Example window rules that are useful

hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    name  = "spotify-workspace",
    match = { class = "^([Ss]potify)$" },

    workspace = "8 silent",
})

hl.window_rule({
    name  = "discord-workspace",
    match = { class = "^(discord)$" },

    workspace = "9 silent",
})

hl.window_rule({
    name  = "notion-workspace",
    match = { class = "^([Nn]otion|notion-app|notion-app-electron)$" },

    workspace = "7 silent",
})

-- Claude Desktop deliberately has NO workspace rule. It is launched on demand and
-- should open on the active workspace; relaunching it while it is open jumps to
-- its window instead (see ~/.local/bin/claude-focus-or-launch and the desktop
-- entry override in ~/.local/share/applications/). To pin it again, restore:
--   hl.window_rule({ name = "claude-workspace",
--       match = { class = "^(com\\.anthropic\\.[Cc]laude(-desktop)?|[Cc]laude)$" },
--       workspace = "6 silent" })

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


-----------------
---- PLUGINS ----
-----------------

-- Plugins built from local, unpublished sources are listed in ~/.config/hypr/local.lua
-- (plugins = { "/path/to/plugin.so" }), so their paths stay out of this public repo.
for _, so in ipairs(local_conf.plugins or {}) do
    hl.plugin.load(so)
end
